"""Configuration constants."""

DEFAULT_SERVER = "imap.gmail.com"
DEFAULT_PORT = 993
DEFAULT_MAILBOX = "INBOX"
DEFAULT_QUERY = "ALL"
DELETED_FLAG = r"\Deleted"
BATCH_SIZE = 50
RATE_LIMIT_DELAY = 0.1
CONNECTION_TIMEOUT = 30
MAX_RETRIES = 3
